"""add_multi_tenant_provider_models

Revision ID: 29818539d1b3
Revises: 006777dc97b7
Create Date: 2026-01-15 15:00:26.760217

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29818539d1b3'
down_revision = '006777dc97b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('api_base', sa.String(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('requires_api_key', sa.Boolean(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('supported_models', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_provider_templates_id'), 'provider_templates', ['id'], unique=False)
    op.create_table('user_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['provider_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_providers_id'), 'user_providers', ['id'], unique=False)
    op.create_index(op.f('ix_user_providers_user_id'), 'user_providers', ['user_id'], unique=False)
    op.create_table('user_model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('default_model_name', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['user_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model_type', name='uix_user_model_type')
    )
    op.create_index(op.f('ix_user_model_configs_id'), 'user_model_configs', ['id'], unique=False)
    op.create_index(op.f('ix_user_model_configs_user_id'), 'user_model_configs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_provider_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_ai_models_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_model_name'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context_window', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_models_pkey'))
    )
    op.create_index(op.f('ix_ai_models_model_name'), 'ai_models', ['model_name'], unique=True)
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('api_base', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_key_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('providers_pkey'))
    )
    op.create_index(op.f('ix_providers_provider_name'), 'providers', ['provider_name'], unique=True)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.drop_index(op.f('ix_user_model_configs_user_id'), table_name='user_model_configs')
    op.drop_index(op.f('ix_user_model_configs_id'), table_name='user_model_configs')
    op.drop_table('user_model_configs')
    op.drop_index(op.f('ix_user_providers_user_id'), table_name='user_providers')
    op.drop_index(op.f('ix_user_providers_id'), table_name='user_providers')
    op.drop_table('user_providers')
    op.drop_index(op.f('ix_provider_templates_id'), table_name='provider_templates')
    op.drop_table('provider_templates')
    # ### end Alembic commands ###
