"""add dynamic_tools table

Revision ID: 061b5546cf64
Revises: aee2860107b1
Create Date: 2026-04-03 16:39:17.461530

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '061b5546cf64'
down_revision = 'aee2860107b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('parameters_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_tools_name'), 'dynamic_tools', ['name'], unique=True)
    op.add_column('action_logs', sa.Column('request_tokens', sa.Integer(), nullable=True))
    op.add_column('action_logs', sa.Column('response_tokens', sa.Integer(), nullable=True))
    op.add_column('action_logs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('action_logs', sa.Column('cost', sa.Float(), nullable=True))
    op.create_index(op.f('ix_chat_messages_agent_id'), 'chat_messages', ['agent_id'], unique=False)
    op.drop_index(op.f('user_memories_embedding_hnsw_idx'), table_name='user_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('user_memories', 'embedding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memories', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('user_memories_embedding_hnsw_idx'), 'user_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_chat_messages_agent_id'), table_name='chat_messages')
    op.drop_column('action_logs', 'cost')
    op.drop_column('action_logs', 'total_tokens')
    op.drop_column('action_logs', 'response_tokens')
    op.drop_column('action_logs', 'request_tokens')
    op.drop_index(op.f('ix_dynamic_tools_name'), table_name='dynamic_tools')
    op.drop_table('dynamic_tools')
    # ### end Alembic commands ###
