"""Add agent score history

Revision ID: 076afe8595a2
Revises: 09ddfd4f1e09
Create Date: 2026-04-09 10:03:37.488259

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '076afe8595a2'
down_revision = '09ddfd4f1e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_score_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_duration_ms', sa.Float(), nullable=True),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_score_history_agent_id'), 'agent_score_history', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_score_history_agent_id'), table_name='agent_score_history')
    op.drop_table('agent_score_history')
    # ### end Alembic commands ###
