"""Add graph execution telemetry

Revision ID: 09ddfd4f1e09
Revises: a6c390ce301b
Create Date: 2026-04-09 09:44:01.968789

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '09ddfd4f1e09'
down_revision = 'a6c390ce301b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('tool_calls_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_executions_agent_id'), 'graph_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_graph_executions_node_name'), 'graph_executions', ['node_name'], unique=False)
    op.create_index(op.f('ix_graph_executions_request_id'), 'graph_executions', ['request_id'], unique=False)
    op.create_index(op.f('ix_graph_executions_session_id'), 'graph_executions', ['session_id'], unique=False)
    op.drop_index(op.f('user_memories_embedding_hnsw_idx'), table_name='user_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('user_memories', 'embedding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memories', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('user_memories_embedding_hnsw_idx'), 'user_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_graph_executions_session_id'), table_name='graph_executions')
    op.drop_index(op.f('ix_graph_executions_request_id'), table_name='graph_executions')
    op.drop_index(op.f('ix_graph_executions_node_name'), table_name='graph_executions')
    op.drop_index(op.f('ix_graph_executions_agent_id'), table_name='graph_executions')
    op.drop_table('graph_executions')
    # ### end Alembic commands ###
