"""Add thread state to sessions

Revision ID: 25bd841e5647
Revises: 29818539d1b3
Create Date: 2026-03-31 14:15:32.811268

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '25bd841e5647'
down_revision = '29818539d1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('thread_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'thread_state')
    op.drop_column('chat_sessions', 'status')
    # ### end Alembic commands ###
