"""add feedback to chat_messages

Revision ID: 7be21ca631f3
Revises: d6285ff99414
Create Date: 2026-04-04 21:22:35.056466

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7be21ca631f3'
down_revision = 'd6285ff99414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'feedback')
    # ### end Alembic commands ###
