"""add_tool_calls_to_messages

Revision ID: a6c390ce301b
Revises: f29c61fe6b33
Create Date: 2026-04-05 03:27:53.214583

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a6c390ce301b'
down_revision = 'f29c61fe6b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tool_calls')
    # ### end Alembic commands ###
