"""add phone and update username

Revision ID: adb6a798d9c5
Revises: 061b5546cf64
Create Date: 2026-04-04 16:34:05.895194

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'adb6a798d9c5'
down_revision = '061b5546cf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_memories_embedding_hnsw_idx'), table_name='user_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('user_memories', 'embedding')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'phone')
    op.add_column('user_memories', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('user_memories_embedding_hnsw_idx'), 'user_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
