"""fix_agent_profile_foreign_key_constraint

Revision ID: aee2860107b1
Revises: 25bd841e5647
Create Date: 2026-04-02 14:22:37.304966

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'aee2860107b1'
down_revision = '25bd841e5647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('agent_profiles_model_config_id_fkey'), 'agent_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'agent_profiles', 'provider_models', ['model_config_id'], ['id'])
    op.drop_constraint(op.f('provider_models_provider_id_model_name_key'), 'provider_models', type_='unique')
    op.create_index(op.f('ix_provider_models_id'), 'provider_models', ['id'], unique=False)
    op.create_unique_constraint('uix_provider_model', 'provider_models', ['provider_id', 'model_name'])
    op.add_column('user_memories', sa.Column('importance', sa.Integer(), nullable=True))
    op.add_column('user_memories', sa.Column('source_session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_memories_source_session_id'), 'user_memories', ['source_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memories_source_session_id'), table_name='user_memories')
    op.drop_column('user_memories', 'source_session_id')
    op.drop_column('user_memories', 'importance')
    op.drop_constraint('uix_provider_model', 'provider_models', type_='unique')
    op.drop_index(op.f('ix_provider_models_id'), table_name='provider_models')
    op.create_unique_constraint(op.f('provider_models_provider_id_model_name_key'), 'provider_models', ['provider_id', 'model_name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'agent_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('agent_profiles_model_config_id_fkey'), 'agent_profiles', 'user_model_configs', ['model_config_id'], ['id'])
    # ### end Alembic commands ###
